apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kuberenetes
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: docker.io/ajsoni2407/jokebitch:latest
        ports:
        - containerPort: 80
